### ISSUE TITLE
Thank you :) and Suggested Usage

### ISSUE THREAD

**Issue by phil-lgr** [lukeed/console-clear#3]
Thanks for this package, it works well on Windows10.

I used it in a npm script to clear the console before additional script, super useful

```
"console-clear": "node -p \"require('./node_modules/console-clear/index.js')(); (function(){return ''})()\""
```

**Comment by phil-lgr** [comment]
I'm a noob at publishing libs/cli on nodejs, how could we make `console-clear` callable from the cli, i.e. available in `node_modules/.bin` ?

**Comment by lukeed** [comment]
Hi @phil-lgr, I'm glad you like it! 😄 

For bin packages, you need to specify a [`"bin"` key](https://docs.npmjs.com/files/package.json#bin) inside the published `package.json`. It will have to point to a Node.js script.

I don't really have interest in including a binary in this package since I've never had the need, but feel free to do it yourself! 

Closing for that reason, but feel free to ping me if you need help~!

**Comment by phil-lgr** [comment]
Sorry I missed your reply!, Thanks for the bin key in package.json I didn't realize npm had this feature.. 👍

**Comment by lukeed** [comment]
No problem!
